### ISSUE TITLE
[Request] update page or percentage

### ISSUE THREAD

**Issue by joespinoza** [Billiam/hardcoverapp.koplugin#2]
is it posible to aside of updating the book page also add the option of updating the progress in percentage?

**Comment by Billiam** [comment]
It's probably possible to add that, but it would still be sending the page (not percent) to hardcover, since that's what the API supports.

Depending on your needs, you might find that the [automatically track progress](https://github.com/Billiam/hardcoverapp.koplugin/blob/main/README.md#automatically-track-progress) option works better for you, since it does some page number translation.

**Comment by Billiam** [comment]
Added in [0.0.7](https://github.com/Billiam/hardcoverapp.koplugin/releases/tag/0.0.7)!
